### ISSUE TITLE
Module requirements for `ibmq_compile`

### ISSUE THREAD

**Issue by dowusu-antwi** [SupertechLabs/cirq-superstaq#136]
There appears to be a `qiskit` dependence here (discovered while attempting to use `ibmq_compile` for working on Pulse Gates -- this error shows up using `Service` both on the server and locally in `main`):

![css-qiskit-depend](https://user-images.githubusercontent.com/18367737/146091496-c264a3ec-8d5c-4d21-be96-61d6c58b2ba3.png)

**Comment by dowusu-antwi** [comment]
(Discussion with @vtomole) To prevent users from seeing this error, perhaps we should let them know in comments / documentation which requirements they need before running `ibmq_compile`.

**Comment by singular-value** [comment]
👍

**Comment by dowusu-antwi** [comment]
So then would we want to throw a `SuperstaQModuleNotFoundException` before reaching a `ModuleNotFoundError`? I.e., the user would never see a `ModuleNotFoundError`, but the `SuperstaQModuleNotFoundException` with the current error message `'ibmq_compile' requires module 'qiskit'` would remain.

**Comment by richrines1** [comment]
imo the requirements should still be made clear in the documentation/comments, but as a last resort `ibmq_compile` should throw `SuperstaQModuleNotFoundException` if someone still attempts to run it without having `qiskit` installed. However the error should probably be thrown from [`applications_superstaq`](https://github.com/SupertechLabs/applications-superstaq/blob/cdd11553084fb2317a80fb1abe6eaecddd131dd1/applications_superstaq/superstaq_client.py#L247) rather than here

**Comment by knsmith** [comment]
Close if ibmq_compile now works with PR from https://github.com/SupertechLabs/general-superstaq/issues/158

**Comment by knsmith** [comment]
Confirmed that `pip install cirq-superstaq[examples]` prevents the above error using `ibmq_compile`
