### ISSUE TITLE
Catch `ModuleNotFoundError`s and throw  more specific exception

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/cirq-superstaq#51]
@singular-value yeah I'd just set it up to catch `ModuleNotFoundError`s and throw something else - will add it now

_Originally posted by @richrines1 in https://github.com/SupertechLabs/cirq-superstaq/issues/50#issuecomment-912671484_

**Comment by richrines1** [comment]
this ended up being addressed in #50, however currently the error only gets thrown after receiving an unusable result back from the server. eventually it might be better to preempt the server call?

**Comment by singular-value** [comment]
@richrines1 I'm not sure what you mean, can you elaborate?

**Comment by richrines1** [comment]
@singular-value basically the current sequence is something like: 
1. user calls `ibmq_compile()`
2. the client posts a job to the server, which returns a compiled sequence
3. the client throws a `ModuleNotFoundError` when it isn't able unpack the sequence it got back
4. we catch the error and throw a more informative `SupererstaQModuleNotFoundException`

it seems like it would be better to bypass step 2 (e.g. by checking for modules explicitly instead of waiting for `ModuleNotFoundError`s), so the client doesn't have to post a job and get a result back just to find out it can't use it. so basically:
1. user calls `ibmq_compile()`
2. the client checks for the necessary modules (qiskit in this case)
3. the client throws a `SupererstaQModuleNotFoundException`

**Comment by vtomole** [comment]
I agree.

**Comment by singular-value** [comment]
👍 makes sense

**Comment by richrines1** [comment]
i think this was covered/superseded by #219
